CREATE TABLE IF NOT EXISTS Todo(
    id INTEGER AUTO_INCREMENT,
    task TEXT NOT NULL,
    is_complete BOOLEAN DEFAULT 0,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
